### ISSUE TITLE
Andoid App Crash when trying to open the Camera

### ISSUE THREAD

**Issue by macshodan** [skiptools/skip-kit#3]
When trying to open the camera on the Android App the first time it will correctly asks for permission, but after granting them nothing happens.

On successive runs, when trying to open the camera the app crashes with the following error:

`android.os.FileUriExposedException: file:///data/user/0/com.nsg.nsg_app_mp/cache/B291B578-3D62-41B3-B9DA-66CF8F24A3E1.png exposed beyond app through ClipData.Item.getUri()`

I'm getting the error on simulator and actual device.

I've set the permissions in the manifest files as follows:

`
    <uses-feature
            android:name="android.hardware.camera"
            android:required="false" />
        <uses-feature
            android:name="android.hardware.camera.autofocus"
            android:required="false" />

        <uses-permission android:name="android.permission.CAMERA" />
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
        <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
        <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />`

Am I doing something wrong? Do I need other permissions?

Thanks a lot

**Comment by marcprux** [comment]
I haven't encountered that error, but it sounds related to https://developer.android.com/about/versions/nougat/android-7.0-changes#sharing-files (which I found via https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed and https://stackoverflow.com/questions/76415310/android-os-fileuriexposedexception-file-storage-emulated-0-download-filenmae). 

Can you post the stack trace (from `adb logcat`) when the app crashes? I'm wondering how exactly the Uri is being "exposed" outside of the intent…

**Comment by macshodan** [comment]
Thanks for quick reply! :) 

Here's the stack trace:

`2024-08-14 10:37:29.486 21416-21416 AndroidRuntime          pid-21416                            E  FATAL EXCEPTION: main
                                                                                                    Process: com.nsg.nsg_app_mp, PID: 21416
                                                                                                    android.os.FileUriExposedException: file:///data/user/0/com.nsg.nsg_app_mp/cache/279921AE-74B8-4055-BA99-027A049C15A3.png exposed beyond app through ClipData.Item.getUri()
                                                                                                    	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2209)
                                                                                                    	at android.net.Uri.checkFileUriExposed(Uri.java:2410)
                                                                                                    	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:1052)
                                                                                                    	at android.content.Intent.prepareToLeaveProcess(Intent.java:11383)
                                                                                                    	at android.content.Intent.prepareToLeaveProcess(Intent.java:11368)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1757)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5410)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:704)
                                                                                                    	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:244)
                                                                                                    	at androidx.activity.ComponentActivity$activityResultRegistry$1.onLaunch(ComponentActivity.kt:225)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry$register$3.launch(ActivityResultRegistry.kt:199)
                                                                                                    	at androidx.activity.compose.ActivityResultLauncherHolder.launch(ActivityResultRegistry.kt:154)
                                                                                                    	at androidx.activity.compose.ManagedActivityResultLauncher.launch(ActivityResultRegistry.kt:143)
                                                                                                    	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.kt:37)
                                                                                                    	at skip.kit.MediaPickerKt$withMediaPicker$1.invoke$lambda$3(MediaPicker.kt:90)
                                                                                                    	at skip.kit.MediaPickerKt$withMediaPicker$1.$r8$lambda$5WJISk0EpbIxpMZukf-wpzMJD7Q(Unknown Source:0)
                                                                                                    	at skip.kit.MediaPickerKt$withMediaPicker$1$$ExternalSyntheticLambda3.invoke(D8$$SyntheticClass:0)
                                                                                                    	at skip.ui.View$onChange$1.invoke$lambda$1(View.kt:1855)
                                                                                                    	at skip.ui.View$onChange$1.$r8$lambda$3ApmqgB1tNpPdiWo82c9g7dDfIk(Unknown Source:0)
                                                                                                    	at skip.ui.View$onChange$1$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
                                                                                                    	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchSideEffects(Composition.kt:1305)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:985)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1005)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:639)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:551)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:775)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@9ed868c, androidx.compose.ui.platform.MotionDurationScaleImpl@56921d5, StandaloneCoroutine{Cancelling}@5d07dea, AndroidUiDispatcher@d1f18db]`

I've just posted the error related part. Let me know if you need anything else to help.

Thanks!

**Comment by marcprux** [comment]
Does the crash occur when you initially open the camera, or after you try to take/select a photo? The `file:///data/user/0/com.nsg.nsg_app_mp/cache/279921AE-74B8-4055-BA99-027A049C15A3.png` URL makes it sound like an image is being selected.

Does the exception look the same both on the device and on the emulator?

It may be that you need to declare the "androidx.core.content.FileProvider" in the manifest as mentioned in the referenced StackOverflow posts, but I haven't needed to do that, and I don't experience that crash.

The only other thing I can think of is whether you have `<uses-feature android:name="android.hardware.camera" android:required="false" />` in your manifest? For reference, this is what my working `AndroidManifest.xml` looks like:


```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This AndroidManifest.xml template was generated by Skip -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false" />

    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <application
        android:label="${PRODUCT_NAME}"
        android:name=".AndroidAppMain"
        android:supportsRtl="true"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:configChanges="orientation|screenSize|screenLayout|keyboardHidden|mnc|colorMode|density|fontScale|fontWeightAdjustment|keyboard|layoutDirection|locale|mcc|navigation|smallestScreenSize|touchscreen|uiMode"
            android:theme="@style/Theme.AppCompat.DayNight.NoActionBar"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
```

**Comment by macshodan** [comment]
The crash appears as soon as I try to open the camera, the media picker works fine.

The first time I try to access the camera on a newly installed build it asks for permissions to access the camera, when granted nothing happens. No matter how many times I try to tap the button (but that might be an issue with the binding boolean not resetting correctly).

Anyway as soon as I tab the camera button again the crash occurs.

My manifest looks like almost identical to yours:
`<?xml version="1.0" encoding="utf-8"?>

<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
    
    
    

    
    <uses-permission android:name="android.permission.INTERNET" />
    
    
    
    <uses-feature
            android:name="android.hardware.camera"
            android:required="false" />
        <uses-feature
            android:name="android.hardware.camera.autofocus"
            android:required="false" />

        <uses-permission android:name="android.permission.CAMERA" />
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
        <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
        <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />

    <application
        android:label="${PRODUCT_NAME}"
        android:name=".AndroidAppMain"
        android:supportsRtl="true"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:configChanges="orientation|screenSize|screenLayout|keyboardHidden|mnc|colorMode|density|fontScale|fontWeightAdjustment|keyboard|layoutDirection|locale|mcc|navigation|smallestScreenSize|touchscreen|uiMode"
            android:theme="@style/Theme.AppCompat.DayNight.NoActionBar"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>                    
    </application>
</manifest>
`

**Comment by marcprux** [comment]
Very strange. You mentioned this happens on *both* the Android emulator as well as the device? Can you post the specified URL in the `android.os.FileUriExposedException` for both the device and emulator? And is that URL the same for each crash, or does it change each time?

I'm assuming that other apps with camera selectors are working on the device, but it might be worthwhile to check. What is the device make and model?

**Comment by macshodan** [comment]
Yes, sorry I don't have the device with me at the moment. I've tried on a couple of Samsung devices.

Right now I'm testing it on the simulator on a couple of virtual devices, a Pixel 8 with API 35 and a Pixel 6a with API 32.

In the meantime I can check multiple times to see if the url changes every time and let you know, then as soon as I can try on another real device I'll let you know.

**Comment by macshodan** [comment]
Here's two consecutive tries:

```
file:///data/user/0/com.nsg.nsg_app_mp/cache/CE99982B-605B-4915-BD63-44D3DD1C9C60.png

file:///data/user/0/com.nsg.nsg_app_mp/cache/50705666-B186-4595-B52D-4C9667737E27.png

```
so the Uri changes every time. I suspect it's some sort of placeholder the simulator uses instead of accessing the real camera. 
The odd thing is that I've checked that directory (using android studio device explorer) and there's no such file in the cache directory.

I have to try on a real device and report back to you.

**Comment by macshodan** [comment]
Hi again, I managed to make more tests on a real device, specifically a Samsung A14 with Android 14 installed.

The crash occurs exactly as it happens on the simulator, but I noticed something different in the logcat.

First that's how I invoke the camera:

```
Button(action: {
                        showCamera = true
                    }, label: {
                        Text("Scatta Foto")
                    })
                    .buttonStyle(.borderedProminent)
                    .withMediaPicker(type: .camera, isPresented: $showCamera, selectedImageURL: $photoUrl)
```

Then I noticed on the logcat that just before crashing it outputs this:

```
10:45:42.261  I  takePictureLauncher: takePictureLauncher.launch: file:///data/user/0/com.nsg.nsg_app_mp/cache/4EDD9804-FDC0-4A11-86CE-607A3456D898.png
```

and just right after it crash with this error:

```
10:45:42.284  E  FATAL EXCEPTION: main
                 Process: com.nsg.nsg_app_mp, PID: 29077
                 android.os.FileUriExposedException: file:///data/user/0/com.nsg.nsg_app_mp/cache/4EDD9804-FDC0-4A11-86CE-607A3456D898.png exposed beyond app through ClipData.Item.getUri()
                 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2245)
                 	at android.net.Uri.checkFileUriExposed(Uri.java:2405)
                 	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:1085)
                 	at android.content.Intent.prepareToLeaveProcess(Intent.java:12743)
                 	at android.content.Intent.prepareToLeaveProcess(Intent.java:12728)
                 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1872)
                 	at android.app.Activity.startActivityForResult(Activity.java:5760)
                 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:704)
                 	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:244)
                 	at androidx.activity.ComponentActivity$activityResultRegistry$1.onLaunch(ComponentActivity.kt:225)
                 	at androidx.activity.result.ActivityResultRegistry$register$3.launch(ActivityResultRegistry.kt:199)
                 	at androidx.activity.compose.ActivityResultLauncherHolder.launch(ActivityResultRegistry.kt:154)
                 	at androidx.activity.compose.ManagedActivityResultLauncher.launch(ActivityResultRegistry.kt:143)
                 	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.kt:37)
                 	at skip.kit.MediaPickerKt$withMediaPicker$1.invoke$lambda$3(MediaPicker.kt:90)
                 	at skip.kit.MediaPickerKt$withMediaPicker$1.$r8$lambda$5WJISk0EpbIxpMZukf-wpzMJD7Q(Unknown Source:0)
                 	at skip.kit.MediaPickerKt$withMediaPicker$1$$ExternalSyntheticLambda3.invoke(D8$$SyntheticClass:0)
                 	at skip.ui.View$onChange$1.invoke$lambda$1(View.kt:1942)
                 	at skip.ui.View$onChange$1.$r8$lambda$3ApmqgB1tNpPdiWo82c9g7dDfIk(Unknown Source:0)
                 	at skip.ui.View$onChange$1$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
                 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchSideEffects(Composition.kt:1374)
                 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:993)
                 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1013)
                 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:685)
                 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:585)
                 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
                 	at android.view.Choreographer.doFrame(Choreographer.java:1069)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:230)
                 	at android.os.Looper.loop(Looper.java:319)
                 	at android.app.ActivityThread.main(ActivityThread.java:8919)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@dc9953e, androidx.compose.ui.platform.MotionDurationScaleImpl@6419f9f, StandaloneCoroutine{Cancelling}@c8d98ec, AndroidUiDispatcher@f6a34b5]
```

Opening the library works without issues.

**Comment by macshodan** [comment]
Update:

I've managed to open the camera interface by adding the following piece of code before showing the picker:

```
val builder = StrictMode.VmPolicy.Builder()
StrictMode.setVmPolicy(builder.build())
```

It doesn't crash the app and it shows the camera correctly. I can take a picture and select it. Unfortunately the binded url is not valid then, so I can't process the image I've took.

If I understood correctly from sdk 24 and up they've added an extra layer of security and you can't access directly an uri outside the app storage, but you need to use a FileProvider. That setting reverted the security policy to before sdk 24, but then I think there's no way to get the file url.

**Comment by marcprux** [comment]
Yes, this seems to be the same issue as discussed at https://stackoverflow.com/questions/75387353/activityresultcontracts-takepicture-it-is-always-returning-false-as-a-result. The problem comes from https://github.com/skiptools/skip-kit/blob/main/Sources/SkipKit/MediaPicker.swift#L69: we create a temporary file and pass it to the `ActivityResultContracts.TakePicture()` to use as the output file for the photo. But it seems like even a temporary file Uri cannot be passed between activities without using a [File Provider](https://developer.android.com/reference/androidx/core/content/FileProvider) and declaring it in the Manifest file.

**Comment by macshodan** [comment]
I see... so if I understand correctly in order to work properly the library needs to be updated and all the projects needs to update their manifest declaring the File Provider used by skip-kit, right?

**Comment by marcprux** [comment]
I've fixed the problem with the camera Uri sharing (https://github.com/skiptools/skip-kit/pull/4) and updated the README at https://github.com/skiptools/skip-kit to describe what you need to do. If you update the version 0.1.3 (`File`/`Packages`/`Update to latest package versions`) and follow the instructions for the `AndroidManifest.xml` and create the `Android/app/src/main/res/xml/file_paths.xml`, then it should work for you.

Ultimately, it should look something like this:

<img width="1676" alt="Screenshot 2024-10-07 at 16 42 46" src="https://github.com/user-attachments/assets/53139fdb-cd10-41ca-914a-f93027aa6d69">

Let us know if you continue to encounter crashes or other issues with the photo picker. Sorry for the trouble!

**Comment by macshodan** [comment]
Wow! 
Thanks a lot! 

I'm going to update and try it now!

**Comment by marcprux** [comment]
Great! Thanks for the help isolating this issue. Hopefully in the future we can find a less fiddly way to add the required metadata on the Android side.
